apiVersion: apps/v1 
kind: Deployment
metadata:
  name: demo-api
spec: 
  selector:
    matchLabels:
      app: demo-api
  replicas: 3 # tells deployment to run 1 pod matching the template
  template:
    metadata:
      labels:
        app: demo-api
    spec:
      containers:
      - name: demo-api
        image: beachcoder/internal:7
        env: 
        - name: DBHOST
          value: "database-server-mariadb"
        - name: DBUSER
          value: "root"
        - name: DBPASSWORD
          valueFrom:
            secretKeyRef:
              name: database-server-mariadb
              key: mariadb-root-password
        - name: DBDATABASE
          value: "events_db"
        - name: SERVICE_PORT
          value: "8082"    
        ports:
        - containerPort: 8082      
